account/urls.py
from django.urls import re_path

from . import views

app_name = "account"

urlpatterns = [
    re_path(r"^signup/$", views.user_signup, name="user_signup"),
    re_path(r"^login/$", views.user_login, name="user_login"),
    re_path(r"^logout/$", views.user_logout, name="user_logout"),
]

detector/urls.py
from django.urls import re_path

from . import views

app_name = "detector"

urlpatterns = [
    re_path(r"^upload-image/$", views.addCropImage, name="add_crop_image"),
    # re_path(r"^predict/(?P<file_path>\w+)/(?P<id>\d+)/", views.predict, name="predict_disease"),
    re_path(r"^predict/", views.predict, name="predict_disease"),
]

forum/urls.py
from django.urls import re_path
from .views import *

app_name = "forum"

urlpatterns = [
    re_path('^$', home, name='home'),
    re_path('^addInForum/', addInForum, name='addInForum'),
    re_path('^addInDiscussion/', addInDiscussion, name='addInDiscussion'),
]

info/urls.py
from django.urls import re_path
from . import views

app_name = "info"

urlpatterns = [
    re_path("weather/", views.weatherView, name="weather"),
    re_path("soil/", views.soilView, name="soil"),
    re_path("set_reminder/", views.setReminderView, name="set_reminder"),
    re_path("get_reminder/", views.getReminderView, name="get_reminder"),
]

website/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path, include
# from django.conf import settings

from detector.views import home

urlpatterns = [
    re_path(r"^$", home, name="home"),
    re_path('^admin/', admin.site.urls),
    re_path("^user/", include("account.urls")),
    re_path("^detect/", include("detector.urls")),
    re_path("^get_info/", include("info.urls")),
    re_path("^forum/", include("forum.urls")),
]

# urlpatterns += [
#     re_path(r'^media/(?P<path>.*)$', django.views.static.serve, {
#     'document_root': settings.MEDIA_ROOT}),]

templates/forum_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DataFlair discussion forum</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    <style>
        .box{
            border: 4px solid green;
            border-radius: 8px;
            margin: 0 auto;
        }
        .forum_topic{
            color: green;
        }
        .home_top{
            /* background-image: url("https://www.world-grain.com/ext/resources/Article-Images/2021/04/Wheat_Photo_cred_adobestock_E.jpg"); */
            background: url("{% static 'images/wheat.jpg' %}");
        }
    </style>
</head>
<body>
    <div class="home_top">
        <h2 class="jumbotron">
            Currently active forums: {{count}}
            <form method="POST" action="{% url 'forum:addInForum' %}">
                {% csrf_token %}
            <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px;">Add more</button>
            </form>
        </h2>
    </div>
            <div class="card-columns" style="padding: 10px; margin: 20px;"></div>
           
            {%for forum in forums %}
           
                <div class="card box container">
                    <br>
                    <h5 class="card-title">
                        <h3 class="forum_topic text-center">{{forum.topic}}</h3>
                    </h5>
                        <div class="card-body container">
                            <p>{{forum.description}}</p>
                            <p> <b>By</b>: {{forum.name}}</p>
                            <p><b>Email</b>: {{forum.email}}</p>
                            <hr style="height:2px;color:green;" />
 
                            <h4>Views from other users</h4>
                            {%for discuss in discussions%}
                            {%for objs in discuss%}  
                            {% if objs.forum == forum %}
                               {{objs.discuss}}
                               <br><br>
                            {% endif %}
                            {%endfor%}
                            {%endfor%}
                            <form method="POST" action="{% url 'forum:addInDiscussion' %}">
                                {% csrf_token %}
                            <button class="btn btn-success" style="width:fit-content; padding: 4px; margin:10px;">Add more</button>
                            </form>
                        </div>
                </div>
            </div>
            <br>
           
            {%endfor%}
         
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Croppable</title>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
	<!-- Font Awesome -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
	<!-- MDB -->
	<link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.css" rel="stylesheet" />
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="icon" type="text/css" href="{% static 'images/favicon.ico' %}">

	<!-- Start of ChatBot code -->
	<script src="https://code.responsivevoice.org/responsivevoice.js?key=4ha2RLzG"></script>
	<!-- End of ChatBot code -->

	<!-- <script type="text/javascript">
		function googleTranslateElementInit() {
			new google.translate.TranslateElement(
				{ pageLanguage: 'en' },
				'google_translate_element'
			);
		}
	</script>

	<script type="text/javascript" src="https://translate.google.com/translate_a/element.js?
  cb=googleTranslateElementInit">
</script> -->


<script src="//code.tidio.co/w5jwnqa3q1cakbt4ynxwncibkgv9l1dx.js" async></script>

	<style>
		* {
			font-family: 'Montserrat' !important;
		}

		#div_1 {
			background-image: url("{% static 'images/Mask_Group.svg' %}");
			background-repeat: no-repeat;
			background-size: 100%;
		}
	</style>

</head>

<body>
</script>
	<div class="container-fluid header2" id="div_1">
		<nav class="navbar navbar-expand-lg navbar-dark">
			<a class="navbar-brand" href="#">
				<img src="{% static 'images/Asset_3_1.svg' %}" height="35px">
				<h3 class="topic" style="margin-left: 20px; font-family: Inter">Croppable</h3>
			</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav flex-row flex-wrap navbar1">
					<li class="nav-item col-lg-auto col-12 col-md-12 How">
						<a class="nav-link active" aria-current="page" href="#How">How it works</a>
					</li>
					<li class="nav-item col-lg-auto col-12 col-md-12 Who">
						<a class="nav-link active" aria-current="page" href="#Who">Who we are</a>
					</li>
					<li class="nav-item col-lg-auto col-12 col-md-12 Contact">
						<a class="nav-link active" aria-current="page" href="#Contact">Contact Us</a>
					</li>

					{% if user.is_authenticated %}
					<li style="margin-left: 40px;">
						<a href="{% url 'account:user_logout' %}"><button type="button"
								class="btn btn-success btn-rounded button4">Log out</button></a>
					</li>

					{% else %}
					<li style="margin-left: 40px;">
						<a href="{% url 'account:user_signup' %}"> <button type="button"
								class="btn btn-success btn-rounded button4">Sign Up</button></a>
					</li>
					<li style="margin-left: 20px;">
						<a href="{% url 'account:user_login' %}"><button type="button"
								class="btn btn-outline-success btn-rounded button5" data-mdb-ripple-color="dark">Log
								In</button></a>
					</li>

					{% endif %}

				</ul>
			</div>
		</nav>


		<div class="container header" style="height:900px">
			<div class="row">
				<div class="col-lg-9">

					<h1 style="margin-left: 30px; color:green; font-size:85px; font-family: Inter">Croppable</h1>
					<h3 style="margin-left: 200px; color:white; font-size:56px; font-family: Inter">Crop Protection App
					</h3>
				</div>
			</div>

		</div>

	</div>

	<div class="container part2">
		<div class="row">
			<h2 class="Line1" id="How">How it Works?</h2>
			<div class="col-lg-3 ps-5 box1 text-center">
				<img src="{% static 'images/remedies.png' %}" style="padding-bottom: 20px">
				<h3 style="font-size:24px; font-family: Inter; margin-top: 10px;font-weight: bold;">Disease Prediction
				</h3>
				<p style="font-size:20px;margin-top: 20px;">Through this website you can identify the disease by
					uploading an image of the plant leaf. A detailed result with all
					parameters of the plant's disease will be displayed on the website.</p>
				<a href="{% url 'detector:add_crop_image' %}"><button type="button"
						class="btn btn-outline-success btn-rounded button1"
						data-mdb-ripple-color="dark">Explore</button></a>
			</div>
			<div class="col-lg-3 ps-5 box3 text-center">
				<img src="{% static 'images/reminder_1.png' %}" style="padding-bottom: 20px">
				<h3 style="font-size:24px; font-family: Inter; margin-top: 10px;font-weight: bold;">Reminders</h3>
				<p style="font-size:20px;margin-top: 20px;">We can set up customised reminders using date and time to
					send notification so that the farmers can provide water and fertilizers to the crops accordingly.
				</p>
				<a href="{% url 'info:set_reminder' %}"><button type="button"
						class="btn btn-outline-success btn-rounded button3" data-mdb-ripple-color="dark">Set
						reminder</button></a>
				<a href="{% url 'info:get_reminder' %}"><button type="button"
						class="btn btn-outline-success btn-rounded button3" data-mdb-ripple-color="dark">Get
						reminder</button></a>
			</div>
			<div class="col-lg-3 ps-5 box1 text-center">
				<img src="{% static 'images/weather_1.png' %}" style="padding-bottom: 20px">
				<h3 style="font-size:24px; font-family: Inter; margin-top: 10px;font-weight: bold;">Weather prediction
				</h3>
				<p style="font-size:20px;margin-top: 20px;">This feature will help us display the weather forecast for
					the next few days so that the farmer can manage the water intake of crops and protect the crops
					according to the weather.</p>
				<a href="{% url 'info:weather' %}"><button type="button"
						class="btn btn-outline-success btn-rounded button1"
						data-mdb-ripple-color="dark">Explore</button></a>
			</div>
			<div class="col-lg-3 ps-5 box2 text-center">
				<img src="{% static 'images/soil_1.png' %}" style="padding-bottom: 20px">
				<h3 style="font-size:24px; font-family: Inter; margin-top: 10px;font-weight: bold;">Soil fertility</h3>
				<p style="font-size:20px;margin-top: 20px;">Using this feature the soil fertility of a certain location
					will be displayed to suggest the farmer to add manures and pesticides to enhance the soil.</p>
				<a href="{% url 'info:soil' %}"><button type="button"
						class="btn btn-outline-success btn-rounded button2"
						data-mdb-ripple-color="dark">Explore</button></a>
			</div>
		</div>
	</div>

	<div class="container header3">
		<div class="row top row1">
			<div class="col-lg-5">
				<img src="{% static 'images/new-laws-on-agriculture-trade-and-contract-farming-in-the-works_1.svg' %}"
					style="height: 450px; width: 430px">
			</div>
			<div class="col-lg-7" id="Who">
				<h3 class="Line9">Who we are?</h3>
				<p class="Line10">This project is an artificially intelligent web app that identifies if your crop is
					diseased. We plan on
					creating a pest detection algorithm that provides farmers with the phone numbers of local pest
					control facilities. We also show effective tips on agriculture and display predicted weather data so
					that farmers can plant their crops accordingly.<br></br> The software provides a dynamic
					dashboard for farmers to keep reminders to water the crop and the prediction system helps the crop
					to be disease-free, this avoids the loss of farmers. The software developed will use statistics and
					visualization to display the results of the predictions in a meaningful manner to the farmers. The
					software developed will also provide an irrigation and weather/season reminder feature.</p>
			</div>
		</div>
	</div>

	<div class="container header4" style="margin-top:100px">
		<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
			<div class="carousel-indicators">
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
					aria-current="true" aria-label="Slide 1"></button>
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
					aria-label="Slide 2"></button>
				<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
					aria-label="Slide 3"></button>
			</div>
			<div class="carousel-inner">
				<center>
					<div class="carousel-item active">
						<img src="{% static 'images/leaf_1.jpg' %}" class="d-flex justify-content-center w-75"
							style="height: 500px; width: 300px">
					</div>
					<div class="carousel-item">
						<img src="{% static 'images/leaf_2.webp' %}" class="d-flex justify-content-center w-75"
							style="height: 500px; width: 300px">
					</div>
					<div class="carousel-item">
						<img src="{% static 'images/leaf_3.jpg' %}" class="d-flex justify-content-center w-75"
							style="height: 500px; width: 300px">
					</div>
				</center>
			</div>
			<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
				data-bs-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true" style="color: black"></span>
				<span class="visually-hidden">Previous</span>
			</button>
			<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
				data-bs-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true" style="color: black"></span>
				<span class="visually-hidden">Next</span>
			</button>
		</div>
	</div>

	<div class="container" id="Contact" style="margin-top: 5%">
		<div class="row">
			<div class="col-lg-6 ps-5 left">
				<h5>Follow Us:</h5>
				<i class="fa fa-facebook "></i>
				<i class="fa fa-twitter "></i>
				<i class="fa fa-instagram "></i>
				<i class="fa fa-linkedin-in "></i>
				<br>
				<br>
				<h5>Information</h5>
				<p>About Croppable</p>
				<p>Get in touch</p>
				<p>Things we like</p>
				<p>Privacy Policy</p>
				<p>Terms and Services</p>
			</div>

			<div class="col-lg-6">
				<h5>Follow Us:</h5>
				<p class="footer"><b>Croppable@gmail.com</b></p>
				<br>
				<h5>KEEP IN TOUCH</h5>
				<form>
					<div class="row" style="margin-bottom: 20px">
						<div class="col">
							<input type="text" class="form-control" placeholder="Name" required="">
						</div>
						<div class="col">
							<input type="text" class="form-control" placeholder="E-mail" required="">
						</div>
					</div>
					<div class="form-outline mb-4 pe-5">
						<textarea class="form-control place3" rows="4" placeholder="Message" required=""></textarea>
					</div>
					<div class="form-check d-flex justify-content-center mb-4 checkbox">
						<input class="form-check-input me-2" type="checkbox" value="" id="form4Example4" checked />
						<label class="form-check-label" for="form4Example4">
							Send me a copy of this message
						</label>
					</div>
					<button type="submit" class="btn btn-warning btn-block mb-4 submit">SUBMIT</button>
				</form>
			</div>
		</div>
	</div>


	<!-- <div class="container-fluid Image1"> -->
	<img src="{% static 'images/Wave.svg' %}" style="width: 100%">
	<!-- </div> -->
	<script src=" https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous">
		</script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.3.0/mdb.min.js"></script>

	<div id="google_translate_element"></div>

	<script type="text/javascript">
		function googleTranslateElementInit() {
		new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
		}
	</script>
	
	<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

</body>

</html>

templates/reminders_view.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Reminders</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
	<link rel="stylesheet" href="{% static 'css/style.css' %}">

  <style>
    * {
			font-family: 'Montserrat' !important;
		}
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        td,
        th {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #dddddd;
        }

        #heading {
            text-align: center;
            color: rgb(9, 81, 9);
        }
    </style>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: white;   box-shadow: 0 2px 4px 0 rgba(0,0,0,.2); ">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/Asset_3_1.svg' %}" height="35px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <h3 class="topic" style="margin-left: 50px; font-family: Inter; color:green;">Croppable</h3>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav flex-row flex-wrap navbar1">
                <li class="nav-item col-lg-auto col-12 col-md-12 How">
                    <a class="nav-link active" aria-current="page" href="#How" style="color:black">How it works</a>
                </li>
                <li class="nav-item col-lg-auto col-12 col-md-12 Who">
                    <a class="nav-link active" aria-current="page" href="#Who" style="color:black">Who we are</a>
                </li>
                <li class="nav-item col-lg-auto col-12 col-md-12 Contact">
                    <a class="nav-link active" aria-current="page" href="#Contact" style="color:black">Contact Us</a>
                </li>

                {% if user.is_authenticated %}
                <li style="margin-left: 40px;">
                    <a href="{% url 'account:user_logout' %}"><button type="button"
                            class="btn btn-success btn-rounded button4">Log out</button></a>
                </li>

                {% else %}
                <li style="margin-left: 40px;">
                    <a href="{% url 'account:user_signup' %}"> <button type="button"
                            class="btn btn-success btn-rounded button4">Sign Up</button></a>
                </li>
                <li style="margin-left: 20px;">
                    <a href="{% url 'account:user_login' %}"><button type="button"
                            class="btn btn-outline-success btn-rounded button5" data-mdb-ripple-color="dark">Log
                            In</button></a>
                </li>

                {% endif %}

            </ul>
        </div>
    </nav>

    <h1 id="heading" style=" font-weight:800;font-family:Inter; color:green; padding: 15px; ; text-align: center;font-size:3rem;margin-top:50px;">Reminders</h1>
    <br>
    <br>

    <div class="container my-2">
        <table>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Date</th>
            </tr>
            {% for reminder in reminders %}
            <tr>
                <th> {{reminder.title}}</th>
                <th>{{reminder.description}}</th>
                <th>{{reminder.datetime}}</th>
            </tr>

            {% endfor %}
        </table>
    </div>

    <br /><br /><br />

	<div id="google_translate_element"></div>

	<script type="text/javascript">
	function googleTranslateElementInit() {
	  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
	}
	</script>
	
	<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

</body>

</html>

templates/soil.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
        integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
	<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>
    

    <title>WEATHER PREDICTION</title>

    <style>
        * {
            margin: 0px;
            padding: 0px;
            box-sizing: border-box;
            margin: 0;
			font-family: 'Montserrat' !important;

            /* background-image: url("clouds.jpeg");
            background-repeat: no-repeat; */

        }

        .border img {
            border-radius: 15px;
            border: 2px solid black;
        }
        .footer{
            /* background-color: rgba(12, 193, 78, 0.326); */
            margin-top: 20px;
            padding: 100px;
            
        }
        .container{
            z-index: -1;
        }
    </style>
</head>

<body  >

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: white;   box-shadow: 0 2px 4px 0 rgba(0,0,0,.2); ">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/Asset_3_1.svg' %}" height="35px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <h3 class="topic" style="margin-left: 50px; font-family: Inter; color:green;">Croppable</h3>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav flex-row flex-wrap navbar1">
                <li class="nav-item col-lg-auto col-12 col-md-12 How">
                    <a class="nav-link active" aria-current="page" href="#How" style="color:black">How it works</a>
                </li>
                <li class="nav-item col-lg-auto col-12 col-md-12 Who">
                    <a class="nav-link active" aria-current="page" href="#Who" style="color:black">Who we are</a>
                </li>
                <li class="nav-item col-lg-auto col-12 col-md-12 Contact">
                    <a class="nav-link active" aria-current="page" href="#Contact" style="color:black">Contact Us</a>
                </li>

                {% if user.is_authenticated %}
                <li style="margin-left: 40px;">
                    <a href="{% url 'account:user_logout' %}"><button type="button"
                            class="btn btn-success btn-rounded button4">Log out</button></a>
                </li>

                {% else %}
                <li style="margin-left: 40px;">
                    <a href="{% url 'account:user_signup' %}"> <button type="button"
                            class="btn btn-success btn-rounded button4">Sign Up</button></a>
                </li>
                <li style="margin-left: 20px;">
                    <a href="{% url 'account:user_login' %}"><button type="button"
                            class="btn btn-outline-success btn-rounded button5" data-mdb-ripple-color="dark">Log
                            In</button></a>
                </li>

                {% endif %}

            </ul>
        </div>
    </nav>

        <h4 style=" font-weight:800;font-family:Inter; color:green; padding: 15px; ; text-align: center;font-size:3rem;margin-top:50px;" >Soil Information</h4>    

   <br>
   <br>

    <div class="container my-2">

        <center>
            
            <div class="row mb-2" style="margin-left: 35%;">

            <div class="col-sm-6" >

                <div class="details" style="margin-top: 10px;">
					
					<h5 class=""><b> Surface Temperature : </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{soil_data.t0}}
                    </br></br></br>
                    </h5>
                    <h5><b> Temperature at 10cms depth: </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{soil_data.t10}}
                    </br></br></br> 
                    </h5>
                    <h5><b> Moisture: </b> </h5>
                    <h5 style="margin-top: 20px;">
                        {{soil_data.moisture}}
                    </br></br></br>
                    </h5>
                    
                </div>
            </div>
        </div>

    </center>

    </div>

    <!-- <div class="footer"></div> -->

	<div id="google_translate_element"></div>

	<script type="text/javascript">
	function googleTranslateElementInit() {
	  new google.translate.TranslateElement({pageLanguage: 'en'}, 'google_translate_element');
	}
	</script>
	
	<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

</body>

</html>